# Generated by Django 4.2.6 on 2023-10-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(max_length=500)),
                ('sevice_body', models.TextField(max_length=500, null=True)),
                ('sevice_name', models.CharField(max_length=50, null=True)),
                ('services_avatar', models.ImageField(null=True, upload_to='photos/services')),
            ],
        ),
        migrations.CreateModel(
            name='testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimony_name', models.CharField(max_length=50)),
                ('testimonies_avatar', models.ImageField(blank=True, upload_to='photos/testimonies')),
                ('testimony_body', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'testimony',
                'verbose_name_plural': 'testimonies',
            },
        ),
    ]
