# Generated by Django 4.2.6 on 2023-10-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='university',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
