# Generated by Django 4.2.6 on 2023-10-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_service_remove_about_services_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_body',
        ),
    ]
